#!/bin/sh

# map caps lock to esc
setxkbmap -option caps:escape

xrandr --auto \
	 --output DP-3 --primary --right-of DP-2

[ -f "${XDG_CONFIG_HOME:=$HOME/.config}/x11/xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"

eval "$(dbus-launch --exit-with-x11 --sh-syntax)"

autostart="xcompmgr-simple-opacity dunst slstatus sxhkd randwall mpdscribble"

for program in $autostart; do
	pidof -sx "$program" && continue
	"$program" > "${XDG_CACHE_HOME:-$HOME/.cache}/autostart.log/$program" 2>&1 &
done >/dev/null 2>&1

dwm
