#!/bin/sh
xrandr --auto \
	 --output eDP-1 --primary --right-of DP-2-2

[ -f "$XDG_CONFIG_HOME/x11/xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"

dunst & # notify-send daemon
slstatus & # dwm statusbar
pipewire & # AV device server

dwm
