library_tabs = ["playlists", "artists", "albums", "browse"]
statusbar_format = "%title - %artists - %album"
flip_status_indicators = true
cover_max_scale = 1.1

[track_format]
left   = "%title"
center = "%artists - %album"

[keybindings]
"Ctrl+r"  = "reconnect"
"Ctrl+d"  = "move pagedown 0.5"
"Ctrl+u"  = "move pageup 0.5"
"Ctrl+f"  = "move pagedown 1"
"Ctrl+b"  = "move pageup 1"
"Esc"     = "back"
"g"       = "move top"
"G"       = "move bottom"
"Shift+q" = "queue"

[credentials]
username_cmd = "echo 6lcfj9m8iwkmpwvfadbt4i1r8"
password_cmd = "pass media/spotify"
